### ISSUE TITLE
Profile Model

### ISSUE THREAD

**Issue by phamelink** [BastienFaivre/ExchangeHub#4]
We need to implement the profile model in redux.

We start with the profile, and then we continue with the rest. With redux we can easily combine state and reducers so starting this way is okay.

I think the profile model will have three main parts to it: courses, tips and personal info. We can also a form state that we persist, so if the user starts filling out a course review and he leaves, he can always come back to it. 

I was thinking of something like this: 

```js
{
	profile: {
		courses: [
			{
				id: 123, // ID of course on kth courses api
				title: "Web dev",
				description: "course about web dev",
				url: "https://kth.se/webdevcourse",
				equivalentEPFL: "func prog",
				stars: 3.5,
				receivedGrade: "A",
				review: "it was good",
			},
		],
		tips: [
			{
				type:
					"housing" ||
					"grocery shopping" ||
					"nightlife" ||
					"travelling" ||
					"visa",
				title: "How I got housing",
				description: "It was difficult",
			},
		],
		info: {
			nationality: "CH",
			section: "Computer Science" || "Biology",
			year: 2021,
		},
		form: {
			courses: {
				id: 123, // ID of course on kth courses api
				title: "Web dev",
				description: "course about web dev",
				equivalentEPFL: "func prog",
				review: "still busy doing it",
			},
			tips: {
				type: "housing",
				title: "How I got housing",
				description: "Still thinking what to write...",
			},
			info: {
				nationality: "NL",
			},
		},
	},
}
```

Of course, we can always discuss this, but I thought the user can always have "ongoing forms" that we persist. Then, once he submits a form, the form is reset to 0 and the corresponding field is updated.

**Comment by ermiashabtegabr** [comment]
Is it necessary to have the ´´info´´ field in the form?
